---
# tasks file for buildbot
- apt: name=python3-pip state=present

- pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - buildbot[bundle]
    - buildbot-grid-view

- name: verify Buildbot installation 
  shell: |
    buildbot --version
  register: buildbot
  
- debug:
    msg: "Buildbot version is {{ buildbot.stdout }} XXX"

- group: name=buildbot state=present system=yes

- user: name=buildbot group=buildbot shell=/bin/bash 

- command: buildbot create-master ~/master
  sudo: yes
  sudo_user: buildbot

- name: here
  copy:
    remote_src: yes
    src: /home/buildbot/master/master.cfg.sample
    dest: /home/buildbot/master/master.cfg
