---
# tasks file for buildbot
- name: get python3-pip
  apt: name=python3-pip state=present update_cache=yes

- pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - buildbot[bundle]
    - buildbot-grid-view

- name: verify Buildbot installation 
  shell: |
    buildbot --version
  register: buildbot
  
- debug:
    msg: "Buildbot version is {{ buildbot.stdout }} XXX"

- group: name=buildbot state=present system=yes

- user: name=buildbot group=buildbot shell=/bin/bash generate_ssh_key=yes

- command: buildbot create-master ~/master
  become: true
  become_method: su
  become_user: buildbot

- name: start buildbot
  copy:
    remote_src: yes
    src: /home/buildbot/master/master.cfg.sample
    dest: /home/buildbot/master/master.cfg
    owner: buildbot

- lineinfile:
    dest: /home/buildbot/master/master.cfg
    state: present
    regexp: "^c\\[\\'buildbotURL\\'\\] = \"http://localhost:8010/\""
    line: "c['buildbotURL'] = \"http://{{ server_name }}:8010/\""

- lineinfile:
    dest: /home/buildbot/master/master.cfg
    state: present
    regexp: "^c\\[\\'www\\'\\] = dict\\(port=8010,"
    line: "c['www'] = dict(port=8011,"

- lineinfile:
    dest: /home/buildbot/master/master.cfg
    state: present
    regexp: "^c\\[\\'protocols\\'\\] = {\\'pb\\': {\\'port\\': 9989}}"
    line: "c['protocols'] = {'pb': {'port': 'tcp:9989:interface=127.0.0.1'}}"
  notify:
    - start buildbot


